# This is an example for local development!
version: "3.7"

services:
  app_server:
    image: shopware-production:local
    build: .
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      # define yourself
      #- DATABASE_URL
      - APP_URL=http://docker.vm:8000
      - INSTANCE_ID=
      - SHOPWARE_ES_ENABLED=1
      - SHOPWARE_ES_HOSTS=elasticsearch:9200
      - SHOPWARE_ES_INDEXING_ENABLED=1
      - SHOPWARE_ES_INDEX_PREFIX=sw
      - SHOPWARE_CDN_STRATEGY_DEFAULT=id
      - MAILER_URL=smtp://localhost:25?encryption=&auth_mode=
    volumes:
      # - "./:/var/www/html"
      - "./config/jwt:/sw6/config/jwt"
      - "./public/bundles:/sw6/public/bundles"
      - "./public/media:/sw6/public/media"
      - "./public/sitemap:/sw6/public/sitemap"
      - "./public/theme:/sw6/public/theme"
      - "./public/thumbnail:/sw6/public/thumbnail"
      - "./var:/sw6/var"

  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]

#  elasticsearch:
#    image: elastic/elasticsearch:7.9.0
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - discovery.type=single-node
